### ISSUE TITLE
Addon hangs on Ubuntu 16.04

### ISSUE THREAD

**Issue by podarok** [balbusm/xul-ext-eds-calendar#13]
Hey there
I've tested 1:38.7.2 Thunderbird for 16.04 ubuntu and got it frozen with this plugin
Upgrade to thunderbird-beta ( 1:45.0~b2 ) gave no luck
So removed the plugin for getting it working

**Comment by balbusm** [comment]
I tested on fresh installation of Ubuntu 16.04 + Thunderbird 38.7.2 + EDS Calendard Integration 0.4.3 and it works perfectly fine.
Please provide me logs.

Enabling addon logging:
1. In Thunderbird go to Preferences > Preferences > Advanced > Config Editor
2. Set entry "extensions.edscalendar.logging.enabled" to true
3. Close Thunderbird
4. Start Thunderbird from terminal
5. Logs should start displaying on the screen.

**Comment by orschiro** [comment]
Dear @balbusm,

I have a similar problem on Ubuntu 16.10 and Thunderbird 45.5.1.

I installed your add-on in response to this [1] question. 

After having installed your add-on, Thunderbird refuses to start and crashes instead.

Can it be the same problem?

Yours,

-Robert

[1] http://askubuntu.com/questions/847494/how-can-i-integrate-thunderbird-lightning-calendar-into-the-unity-message-indica?noredirect=1#comment1326932_847494

**Comment by balbusm** [comment]
Could you get logs for me?
- Uninstall add-on
- In Thunderbird go to Preferences > Preferences > Advanced > Config Editor
- Set entry "extensions.edscalendar.logging.enabled" to true
- Close Thunderbird
- Install add-on
- Start Thunderbird from terminal
- Logs should start appearing

**Comment by orschiro** [comment]
Thanks for your help!

However, I don't have this entry:

![image](https://cloud.githubusercontent.com/assets/170947/21193667/57cea674-c22d-11e6-942b-22e6e7b7d029.png)

**Comment by balbusm** [comment]
Could you add such an entry? Set value to true and do the other steps.

**Comment by orschiro** [comment]
That worked. :-)

Does that help?

```
orschiro@x230:~$ thunderbird 
[calBackendLoader] Using libical backend at /usr/lib/thunderbird/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}/components/libical-manifest
*** LOG edscalendar.utils: Opened libglib-2.0.so.0
*** LOG edscalendar.utils: Opened libgio-2.0.so.0
*** LOG edscalendar.utils: Opened libgobject-2.0.so.0
*** LOG edscalendar.utils: Opened libical.so.1
*** LOG edscalendar.utils: Opened libedataserver-1.2.so.22
*** LOG edscalendar.utils: Opened libecal-1.2.so.19
*** LOG edscalendar.libecal: Loading new declaration of e_cal_client_connect_sync...
*** LOG edscalendar.libecal: Successfully loaded e_cal_client_connect_sync
*** LOG edscalendar.edsCalendarClient: Adding events for calendar Google Calendar - 9d8ba6b3-9c0d-4571-86b5-f938157b5a66
*** LOG edscalendar.edsCalendarClient: Processing item Molly & Tom return - lihirt2o6itrgilbq2gfiv2qvg@google.com
*** LOG edscalendar.calEDSProvider: Getting ERegistry...
*** LOG edscalendar.calEDSProvider: Getting ESource...
*** LOG edscalendar.calEDSProvider: Created new source for calendar Google Calendar - 9d8ba6b3-9c0d-4571-86b5-f938157b5a66
*** LOG edscalendar.calEDSProvider: Connecting ECalClient...
*** LOG edscalendar.calEDSProvider: Saved ECalClient for batch mode
*** LOG edscalendar.calEDSProvider: ECalClient is ready to use!
*** LOG edscalendar.calEDSProvider: Looking for an item...
*** LOG edscalendar.calEDSProvider: Couldn't find an item
```

**Comment by balbusm** [comment]
There is no error.
Could you install more verbose version of the addon and show the logs: 
https://github.com/balbusm/xul-ext-eds-calendar/blob/bugfix/13-addon-hangs/output/xul-ext-eds-calendar.xpi

**Comment by orschiro** [comment]
This version is not crashing. However, it is very slow. 

What am I supposed to see now? I did not notice any changes.

I was hoping to see a calendar entry in the following menu.

![image](https://cloud.githubusercontent.com/assets/170947/21331609/a81e8f76-c643-11e6-8d63-2efab1b11112.png)

**Comment by balbusm** [comment]
I added more verbose logging, maybe it slows down TB.
Which version of addon did you use?
Could you install addon from Mozilla site and check if slowness occurs?
You can also disable logging.

Calendar entry is visible in clock menu:
![image](https://cloud.githubusercontent.com/assets/6872448/21347549/657f95e6-c6a9-11e6-903c-1c3000cd53c6.png)

**Comment by orschiro** [comment]
Hey, it is no longer crashing. Thank you. :-)

But I don't see any entry in the calendar indicator. 

Do I have to configure something else? Or doesn't it work with Lightning and Google Calendar?

-R

**Comment by balbusm** [comment]
There is no configuration required, it should work out of the box.
Could you run Thunderbird from command line and get the logs again?

**Comment by orschiro** [comment]
Hi @balbusm,

I thank you for your help!

Does that help?

```
*** ERROR edscalendar.calEDSProvider: Couldn't connect to source: (15) Unable to connect to 'Home': Backend factory for source '4fa8690c-8303-496a-bd59-89dadb7ed394' and extension 'Task List' cannot be found.
*** ERROR edscalendar.calEDSProvider: CalendarServiceException@resource://edscalendar/exceptions.jsm:26:13
checkGError@jar:file:///home/orschiro/.thunderbird/hjov4sbz.default/extensions/%7Be6696d02-466a-11e3-a162-04e36188709b%7D.xpi!/components/calEDSProvider.js:209:15
getECalClient@jar:file:///home/orschiro/.thunderbird/hjov4sbz.default/extensions/%7Be6696d02-466a-11e3-a162-04e36188709b%7D.xpi!/components/calEDSProvider.js:333:9
adoptItem@jar:file:///home/orschiro/.thunderbird/hjov4sbz.default/extensions/%7Be6696d02-466a-11e3-a162-04e36188709b%7D.xpi!/components/calEDSProvider.js:546:18
addItem@jar:file:///home/orschiro/.thunderbird/hjov4sbz.default/extensions/%7Be6696d02-466a-11e3-a162-04e36188709b%7D.xpi!/components/calEDSProvider.js:597:16
processItem@chrome://edscalendar/content/edsCalendarClient.js:135:11
asyncLoopInternal@chrome://edscalendar/content/edsCalendarClient.js:92:9

*** ERROR edscalendar.edsCalendarClient: Operation add on element null failed. 2147500037 - Couldn't connect to source: (15) Unable to connect to 'Home': Backend factory for source '4fa8690c-8303-496a-bd59-89dadb7ed394' and extension 'Task List' cannot be found.
```

**Comment by balbusm** [comment]
Could you send me entire log?
You can call:
thunderbird > log.txt

**Comment by orschiro** [comment]
Yes, of course. 

Please see my attached file. :-)

[log.txt](https://github.com/balbusm/xul-ext-eds-calendar/files/666101/log.txt)

**Comment by balbusm** [comment]
From the logs everything looks fine, all your events were added to calendar indicator. 
Those errors are expected, since addon cannot add tasks (only calendar events). Nothing to worry about.
In your calendar indicator click on a day before your event maybe then it will be reloaded.

**Comment by orschiro** [comment]
Never mind then.

The problem must be somewhere on my system but it is not such a 
priority. :-)

Yours,

-R

**Comment by balbusm** [comment]
Issue not observed on version 0.5

**Comment by brunhi** [comment]
Hi there,
Ubuntu-gnome,16.04 LTS, 4.4.0-64-generic
Thunderbird 45.7.0

I was trying to run the add-on, but unfortunately Thunderbird hangs on 'Loading...' whenever both, the 'lightning' and 'eds integration' add-ons are enabled in parallel. Thunderbird does not crash, but simply hangs at the 'Loading...' screen forever (>60min), I tried this with an empty calender aswell; the issue persists.
See below my log when running $ thunderbird from the terminal:

[calBackendLoader] Using libical backend at /home/USER/.thunderbird/XXXXXXXX.default/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}/components/libical-manifest
*** LOG edscalendar.edsCalendarClient: Init start
*** LOG edscalendar.utils: Opened libglib-2.0.so.0
*** LOG edscalendar.utils: Opened libgio-2.0.so.0
*** LOG edscalendar.utils: Opened libgobject-2.0.so.0
*** LOG edscalendar.utils: Opened libical.so.1
*** LOG edscalendar.utils: Opened libedataserver-1.2.so.20
*** LOG edscalendar.utils: Opened libecal-1.2.so.18
*** LOG edscalendar.libecal: Loading new declaration of e_cal_client_connect_sync...
*** LOG edscalendar.libecal: Successfully loaded e_cal_client_connect_sync
*** LOG edscalendar.edsCalendarClient: Init finished
*** LOG edscalendar.calEDSProvider: Getting ERegistry...
*** LOG edscalendar.calEDSProvider: Getting ESource...

(thunderbird:7673): GLib-GObject-WARNING **: cannot register existing type 'CamelObject'

(thunderbird:7673): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(thunderbird:7673): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed

(thunderbird:7673): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(thunderbird:7673): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(thunderbird:7673): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed

(thunderbird:7673): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(thunderbird:7673): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(thunderbird:7673): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed

(thunderbird:7673): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(thunderbird:7673): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed

(thunderbird:7673): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
