### ISSUE TITLE
Fedora 28 - core dumped

### ISSUE THREAD

**Issue by pszypowicz** [balbusm/xul-ext-eds-calendar#21]
I remove `evolution-ews` and unfortunately I still got: 

`Segmentation fault (core dumped)`

```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 28 (Twenty Eight)
Release:	28
Codename:	TwentyEight
$ uname -a
Linux laptop 4.17.3-200.fc28.x86_64 #1 SMP Tue Jun 26 14:17:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by balbusm** [comment]
Couldn't reproduce it on vanilla Fedora version.
Could you turn on EDS Calendar Integration logging? You should be able to do it right after installation, before you restart TB. 
Did you try to uninstall evolution-mapi?

**Comment by pszypowicz** [comment]
Unfortunately I had to switch notebooks very recently, so I did fresh installation of Fedora 28 anyway, and this time your extension works flawlessly. (My previous setup though, was fedora updated every release since F24)

I suggest to remove this issue, since no further investigation is impossible, and I created this ticket so I could help with that.
