### ISSUE TITLE
Join TbSync for unified UI

### ISSUE THREAD

**Issue by jobisoft** [balbusm/xul-ext-eds-calendar#22]
I try to evolve TbSync into "the" central sync manager for contacts, tasks and events of external accounts for Thunderbird. Currently supporting CalDAV/CardDAV and EAS (ActiveSync). EWS is being worked on (Exchange WebServices).

TbSync offers an API to "hook" external providers into TbSync. External providers can re-use most of the UI and only have to provide the core sync functions.

Are you interested in joining? TbSync and its API is ready for Thunderbird 60+. An example of an external provider is the CalDAV/CardDAV provider:
https://addons.thunderbird.net/en-US/thunderbird/addon/dav-4-tbsync/

I will provide you with all the help you need, if you are interested.

Edit: remove redundancy

**Comment by balbusm** [comment]
How can I help you?
What would you like to achieve with EDS Integration?

**Comment by balbusm** [comment]
I'm hapy to help but I'm not sure how EDS Integration addon fits into TbSync. EDS Integration addon puts all Thunderbird calendars events into EDS (evolution data server). Synchronization is unidirectional. 
How EDS Integration can use TbSync?
I think TbSync requires oposite direction Evolution -> TB or bidirectional sync. Moreover only EDS events should be synchronized.
I could create separate plugin for that.

**Comment by jobisoft** [comment]
That is true, I thought your AddOn is bi-directional and makes Thunderbird an "EDS client", so the GNOME system calendar (which is stored in EDS I think) will be fully available in Thunderbird as the "EDS calendar". So changes made to that central calendar by any other client will show up in Thunderbird and any change made to this calendar in Thunderbird will be available in all other clients.

But if I understood you correct, you add all Thunderbird events (of all active calendars?) to EDS, so they show up in the central GNOME calendar for example? And you do not provide a extra "EDS calendar" in Thunderbird?

That is of course a completely different use case and does not "fit" with TbSync. That is correct.

Question: Does EDS support more than one calendar and more than one address book?

If you see a usecase (and demand) for "the other way around" to make all EDS resources (calendars and address books) available in Thunderbird, you can still jump on TbSync. But I do not want to push you into this work. That was not my intention. I wanted to inform you about TbSync to make things easier for you (specially with regard to the upcoming Thunderbird transitions), but did not want to cause MORE work for you.

**Comment by balbusm** [comment]
Yes use case for EDS Integration is totally different. I want to synchronize Thundebird calendar events with GNOME System calendar in order to show events in Calendar applet (one in system top bar).
 

EDS Integration mirrors (copies) all TB calendars into GNOME calendar (EDS), so you get exacly the same amount of calendars with same names on GNOME Calendar side.


Address book is not synchronized.


I think synchronizing Evolution to TB is very rare case. I will consider developing such a plugin when I see a good use case.

**Comment by jobisoft** [comment]
Understood. Closing this. Thanks for your Feedback!
