### ISSUE TITLE
Thunderbird is very slow to start with this extension

### ISSUE THREAD

**Issue by gregoiregentil** [balbusm/xul-ext-eds-calendar#23]
Thunderbird takes 8 seconds to start with extension, less than 3 seconds without.

The other extension I have are Lighting, two-email-related extensions and Messaging Menu and and Unity Launcher integration.

The log shows something like this: https://pastebin.com/irXaRYm0

**Comment by balbusm** [comment]
Implemented in version 0.7.
Added delay so Thunderbird gets fully loaded before addon start sync
