### ISSUE TITLE
Addon hangs on Debian Buster

### ISSUE THREAD

**Issue by shenron42** [balbusm/xul-ext-eds-calendar#24]
Hello,

Since an upgrade from Debian 9 to 10, Thunderbird (and EDS) stops to work.
No crash, but hangs forever.

If I disable/remove the addon, everything is getting back working.
I tryed to remove and re-install, same issue.

Here the log I have :

(thunderbird:7231): GLib-GObject-WARNING **: 10:01:37.803: cannot register existing type 'CamelObject'
(thunderbird:7231): GLib-CRITICAL **: 10:01:37.803: g_once_init_leave: assertion 'result != 0' failed
(thunderbird:7231): GLib-GObject-CRITICAL **: 10:01:37.803: g_type_register_static: assertion 'parent_type > 0' failed
(thunderbird:7231): GLib-GObject-CRITICAL **: 10:01:37.803: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
(thunderbird:7231): GLib-CRITICAL **: 10:01:37.803: g_once_init_leave: assertion 'result != 0' failed
(thunderbird:7231): GLib-GObject-CRITICAL **: 10:01:37.803: g_type_register_static: assertion 'parent_type > 0' failed
(thunderbird:7231): GLib-GObject-CRITICAL **: 10:01:37.803: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
(thunderbird:7231): GLib-CRITICAL **: 10:01:37.803: g_once_init_leave: assertion 'result != 0' failed
(thunderbird:7231): GLib-GObject-CRITICAL **: 10:01:37.803: g_type_register_static: assertion 'parent_type > 0' failed
(thunderbird:7231): GLib-CRITICAL **: 10:01:37.803: g_once_init_leave: assertion 'result != 0' failed
(thunderbird:7231): GLib-GObject-CRITICAL **: 10:01:37.803: g_type_register_static: assertion 'parent_type > 0' failed
(thunderbird:7231): GLib-CRITICAL **: 10:01:37.803: g_once_init_leave: assertion 'result != 0' failed

Debian Buster (10).
Wayland.
Thunderbird 60.6.1 64bits
EDS 0.5.1

Thanks for you help

**Comment by shenron42** [comment]
Looks like @brunhi got the same issue here :
https://github.com/balbusm/xul-ext-eds-calendar/issues/13#issuecomment-283444512

@brunhi did you found a fix since 2 years ? ^^

**Comment by balbusm** [comment]
Hi,
There are  possible issues that might have happened:
- There is an issue in EDS implementation - see #9 
- There is some change in EDS API (EDS developers tend to break backwards compatibility from time to time)
- It might be an issue with addon that it doesn't reinitialize EDS after system upgrade see  #21 

I will try to run it on vanilla Debian Buster and see how it goes.

**Comment by shenron42** [comment]
Thanks for your answer.

I've done some research before opening this issue :
- evolution-ews already uninstalled
- evolution-mapi not installed (and does not exist in Buster repo)

Dont know how it will react on a vanilly Buster.
I've another computer upgraded from 9 to 10 (64 bits, same version of TB and EDS) and EDS Calendar Integration works flawlessly...

**Comment by balbusm** [comment]
So it must be somehow related to the system/library upgrade.
Did you use EDS Calendar on your second computer before upgrade?
I'm trying to spot the difference between your first and second upgrade.
What could be the differences with usage TB, EDS Calendar on your machines?

**Comment by shenron42** [comment]
I have no idea of the differences between the 2 upgrades :/

The both computers was with Debian 9 64bits.
Global black theme used (I don't know if it can be related to GTK or something...)
TB + EDS Calendar Integration installed and working.

I upgrade the both with the same source.list

Personnal computer is working, the professional one not.

The only difference i can spot is the 50 events to sync on the personnal computer vs several thousand on the professional...

But I removed my calendar, and try to use the addon with a fresh one, it freeze TB with the sames errors.

**Comment by shenron42** [comment]
Wow !

Release 0.5.2 "Fixed issue where addon hanged TB during the start-up" do the job for me !!

Awesome ! Thank you very much !

Where can i buy you a beer ?

**Comment by balbusm** [comment]
Enjoy the addon :)
