### ISSUE TITLE
Extension does not work with Gnome 3.4

### ISSUE THREAD

**Issue by bridnour** [balbusm/xul-ext-eds-calendar#30]
Gnome 3.34 has upgraded libecal from 1.2 to 2.0.
This extension does not run on Gnome 3.34, stating it cannot find libecal-1.2.so.

I tried changing references to libecal-1.2 to libecal-2.0. This causes a segfault. (See attached log file).
[error-log.txt](https://github.com/balbusm/xul-ext-eds-calendar/files/3720161/error-log.txt)

**Comment by balbusm** [comment]
What OS are you using?

**Comment by bridnour** [comment]
I tried it using an updated version of Arch and Ubuntu 19.10 with similar results.

**Comment by mpreyers** [comment]
Same problem with Fedora 31 and Gnome 3.34.

**Comment by knoedelsalat** [comment]
Same here on Manjaro with Gnome 3.34.1

**Comment by devnix** [comment]
Same problem, Ubuntu 19.10

**Comment by balbusm** [comment]
They introduced some breaking changes in Evolution Data Server (EDS)  https://mail.gnome.org/archives/desktop-devel-list/2019-April/msg00016.html
I'm trying to figure out how to port addon to new API.

**Comment by balbusm** [comment]
Fixed in 0.8.
As soon as Thunderbird team reviews addon it will be available via TB store.
Meanwhile you can download it from Release page:
https://github.com/balbusm/xul-ext-eds-calendar/releases/tag/0.8

**Comment by devnix** [comment]
Works perfectly. Thank you!

**Comment by bridnour** [comment]
Here is a slightly late thank you:

Thank you! It works perfectly now,
