### ISSUE TITLE
Question: Is there a way to disable notifications?

### ISSUE THREAD

**Issue by v4rakh** [balbusm/xul-ext-eds-calendar#33]
Is there a way to disable notifications for synced calendars other than setting something like `NotShowIn=GNOME` proposed in a bug report on GNOME's gitlab?

**Comment by balbusm** [comment]
Short answer is no.

The only option at the moment is to uncheck your calendar in Thunderbird. It will cause that your calendar will be hidden so the notifications.

**Comment by v4rakh** [comment]
Ok thanks.
