### ISSUE TITLE
Doesn't work on ubuntu18.04

### ISSUE THREAD

**Issue by kskollepara** [balbusm/xul-ext-eds-calendar#35]
I installed this addon on thunderbird v68, however I still don't see my events on ubuntu calendar. How can I check where the problem lies?
![image](https://user-images.githubusercontent.com/24797363/109129725-3e86a580-7751-11eb-80a6-8ba837ed2fef.png)

**Comment by balbusm** [comment]
Could you gather logs according to description?
https://github.com/balbusm/xul-ext-eds-calendar > Having issues?

**Comment by kskollepara** [comment]
> Could you gather logs according to description?
> https://github.com/balbusm/xul-ext-eds-calendar > Having issues?

Here are the logs:
`console.log: WebExtensions: Loading packed extension from /home/kiran/.thunderbird/60vzxj4n.default-release/extensions/{d5e81018-f07b-4719-b893-3dc450504672}.xpi
console.log: WebExtensions: Loading packed extension from /home/kiran/.thunderbird/60vzxj4n.default-release/extensions/{e6696d02-466a-11e3-a162-04e36188709b}.xpi
console.log: WebExtensions: Loading packed extension from /home/kiran/.thunderbird/60vzxj4n.default-release/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}.xpi
console.log: WebExtensions: Loading add-on preferences from  /home/kiran/.thunderbird/60vzxj4n.default-release/extensions/{e6696d02-466a-11e3-a162-04e36188709b}.xpi
console.log: WebExtensions: Firing profile-after-change listeners for {e6696d02-466a-11e3-a162-04e36188709b}
console.log: WebExtensions: Loading add-on preferences from  /home/kiran/.thunderbird/60vzxj4n.default-release/extensions/{d5e81018-f07b-4719-b893-3dc450504672}.xpi
console.log: WebExtensions: Firing profile-after-change listeners for {d5e81018-f07b-4719-b893-3dc450504672}
console.log: WebExtensions: Loading add-on preferences from  /home/kiran/.thunderbird/60vzxj4n.default-release/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}.xpi
console.log: WebExtensions: Firing profile-after-change listeners for {e2fda1a4-762b-4020-b5ad-a41df1933103}
[calBackendLoader] Using Thunderbird's builtin libical backend
*** 2021-03-01T09:19:24.972Z LOG  edscalendar.edsCalendarClient : Init start
*** 2021-03-01T09:19:24.974Z LOG  edscalendar.utils : Opened libglib-2.0.so.0
*** 2021-03-01T09:19:24.974Z LOG  edscalendar.utils : Opened libgio-2.0.so.0
*** 2021-03-01T09:19:24.974Z LOG  edscalendar.utils : Opened libgobject-2.0.so.0
*** 2021-03-01T09:19:24.993Z LOG  edscalendar.utils : Opened libecal-1.2.so.19
*** 2021-03-01T09:19:24.994Z ERROR  edscalendar.edslib : Library libecal-2.0.so not available. Detected not suported libecal-1.2.so. Addon requires at least EDS 3.33.2
JavaScript error: chrome://edscalendar/content/edsCalendarClient.js, line 42: uncaught exception: LoadingLibException: Library libecal-2.0.so not available. Detected not suported libecal-1.2.so. Addon requires at least EDS 3.33.2
JavaScript error: chrome://edscalendar/content/edsCalendarClient.js, line 42: NS_ERROR_XPC_GS_RETURNED_FAILURE: ServiceManager::GetService returned failure code:
1614590368930	addons.xpi	WARN	Can't get modified time of /usr/lib/thunderbird/features/wetransfer@extensions.thunderbird.net
`

**Comment by kskollepara** [comment]
> Could you gather logs according to description?
> https://github.com/balbusm/xul-ext-eds-calendar > Having issues?

Here are the logs: 


> console.log: WebExtensions: Loading packed extension from /home/kiran/.thunderbird/60vzxj4n.default-release/extensions/{d5e81018-f07b-4719-b893-3dc450504672}.xpi
> console.log: WebExtensions: Loading packed extension from /home/kiran/.thunderbird/60vzxj4n.default-release/extensions/{e6696d02-466a-11e3-a162-04e36188709b}.xpi
> console.log: WebExtensions: Loading packed extension from /home/kiran/.thunderbird/60vzxj4n.default-release/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}.xpi
> console.log: WebExtensions: Loading add-on preferences from  /home/kiran/.thunderbird/60vzxj4n.default-release/extensions/{e6696d02-466a-11e3-a162-04e36188709b}.xpi
> console.log: WebExtensions: Firing profile-after-change listeners for {e6696d02-466a-11e3-a162-04e36188709b}
> console.log: WebExtensions: Loading add-on preferences from  /home/kiran/.thunderbird/60vzxj4n.default-release/extensions/{d5e81018-f07b-4719-b893-3dc450504672}.xpi
> console.log: WebExtensions: Firing profile-after-change listeners for {d5e81018-f07b-4719-b893-3dc450504672}
> console.log: WebExtensions: Loading add-on preferences from  /home/kiran/.thunderbird/60vzxj4n.default-release/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}.xpi
> console.log: WebExtensions: Firing profile-after-change listeners for {e2fda1a4-762b-4020-b5ad-a41df1933103}
> [calBackendLoader] Using Thunderbird's builtin libical backend
> *** 2021-03-01T09:19:24.972Z LOG  edscalendar.edsCalendarClient : Init start
> *** 2021-03-01T09:19:24.974Z LOG  edscalendar.utils : Opened libglib-2.0.so.0
> *** 2021-03-01T09:19:24.974Z LOG  edscalendar.utils : Opened libgio-2.0.so.0
> *** 2021-03-01T09:19:24.974Z LOG  edscalendar.utils : Opened libgobject-2.0.so.0
> *** 2021-03-01T09:19:24.993Z LOG  edscalendar.utils : Opened libecal-1.2.so.19
> *** 2021-03-01T09:19:24.994Z ERROR  edscalendar.edslib : Library libecal-2.0.so not available. Detected not suported libecal-1.2.so. Addon requires at least EDS 3.33.2
> JavaScript error: chrome://edscalendar/content/edsCalendarClient.js, line 42: uncaught exception: LoadingLibException: Library libecal-2.0.so not available. Detected not suported libecal-1.2.so. Addon requires at least EDS 3.33.2
> JavaScript error: chrome://edscalendar/content/edsCalendarClient.js, line 42: NS_ERROR_XPC_GS_RETURNED_FAILURE: ServiceManager::GetService returned failure code:
> 1614590368930	addons.xpi	WARN	Can't get modified time of /usr/lib/thunderbird/features/wetransfer@extensions.thunderbird.net
>

**Comment by balbusm** [comment]
Addon needs libecal lib to work.
Your installed libecal version (libecal-1.2) is not compatible with addon version 0.8.
You need to downgrade addon to version 0.7 which is compatible with lib installed on your machine

Link to version 0.7
https://addons.thunderbird.net/en-US/thunderbird/addon/eds-calendar-integration/versions/?page=1#version-0.7

Let me know if 0.7 works for you.

**Comment by kskollepara** [comment]
> Addon needs libecal lib to work.
> Your installed libecal version (libecal-1.2) is not compatible with addon version 0.8.
> You need to downgrade addon to version 0.7 which is compatible with lib installed on your machine
> 
> Link to version 0.7
> https://addons.thunderbird.net/en-US/thunderbird/addon/eds-calendar-integration/versions/?page=1#version-0.7
> 
> Let me know if 0.7 works for you.

Worked like a charm. Thanks a lot.
