### ISSUE TITLE
Just 2 of my calendars are synchronized

### ISSUE THREAD

**Issue by Kury25** [balbusm/xul-ext-eds-calendar#43]
I've just install today this extension, and only 2 of my calendars are synchronized (my thunderbird version is 78.14.0 (64 bits)).
I get the error :
```
NS_ERROR_XPC_JSOBJECT_HAS_NO_FUNCTION_NAMED: JavaScript component does not have a method named: "getItems"'JavaScript component does not have a method named: "getItems"' when calling method: [calICalendar::getItems] edsCalendarClient.jsm:77
    processCalendars resource://edscalendar/legacy/modules/edsCalendarClient.jsm:77
    asyncLoopInternal resource://edscalendar/legacy/modules/utils/asyncHelper.jsm:61
    asyncLoopInternal resource://edscalendar/legacy/modules/utils/asyncHelper.jsm:62
    jobId resource://edscalendar/legacy/modules/utils/asyncHelper.jsm:72
```
Could you help me please ? Did I miss a step ?
Many thanks

**Comment by balbusm** [comment]
Could you describe those calendars?
What is those calendars type (WebDAV, GMail, etc)?
Do you have some addons installed to support those calendars?

**Comment by Kury25** [comment]
I have a "Outlook" calendar, and others are webdav and ics inline
Some are supported by addon "TbSync" (but the 2 which are ok are under TbSync too).

**Comment by balbusm** [comment]
Could you try below version? 
It adds extra logging.
You should see logs with prefix `processCalendars`
```
*** 2022-01-10T20:02:41.248Z LOG  edscalendar.edsCalendarClient : processCalendars [xpconnect wrapped (nsISupports, nsIClassInfo, calICalendar, calICalendarProvider, calIOfflineStorage, calISchedulingSupport, calISyncWriteCalendar)]
*** 2022-01-10T20:02:41.248Z LOG  edscalendar.edsCalendarClient : processCalendars::has functions
*** 2022-01-10T20:02:41.249Z LOG  edscalendar.edsCalendarClient : processCalendars::name Home
```
Please provide logs and identify which calendar and addon causes missing `getItems` method.

[ext-eds-calendar-0.9.4-tb-linux.zip](https://github.com/balbusm/xul-ext-eds-calendar/files/7841592/ext-eds-calendar-0.9.4-tb-linux.zip)

**Comment by Kury25** [comment]
Thank you, I have identified the reason : I had a "deactivated" calendar on the list. When it came on it, it made the mistake and stopped all processes.
I delete this calendar and now it works for all other calendars.

the log was : 
```
2022-01-11T18:39:18.709Z LOG  edscalendar.edsCalendarClient : processCalendars [xpconnect wrapped (nsISupports, nsIClassInfo, calICalendar, calICalendarProvider, calIOfflineStorage, calISchedulingSupport, calISyncWriteCalendar)]
2022-01-11T18:39:18.709Z LOG  edscalendar.edsCalendarClient : processCalendars::has functions 
2022-01-11T18:39:18.709Z LOG  edscalendar.edsCalendarClient : processCalendars::name sdis25
```
Thanks for your help !!

**Comment by mbalbus** [comment]
Inactive calendar shouldn't be a problem.
Could you tell me what addon backs up this inactive calendar?
