### ISSUE TITLE
Is EDS Calendar Integration working in Thunderbird 102+ ?

### ISSUE THREAD

**Issue by GerryT11** [balbusm/xul-ext-eds-calendar#46]
Soon, the Mozilla PPA team will update Thunderbird on Ubuntu 22.04 to version 102.1.0
Is EDS Calendar Integration working in TB 102+?

I am asking, because the the manifest file shows:
      "strict_max_version": "91.*"

BTW, thanks for the excellent EDS Calendar Integration addon!

**Comment by balbusm** [comment]
No, it won't work with TB 102+ as TB team introduced some changes that are not backward compatible.

See details:
https://developer.thunderbird.net/add-ons/updating/tb102/adapt-to-changes-in-thunderbird-92-102#calicalendar

Adjusting addon to the latest TB is on my roadmap.

**Comment by dsommers** [comment]
If you need help testing, just make a downloadable .xpi available and I'll test it on RHEL-8 with GNOME 3.32.2.  The EDS add-on worked great, until Thunderbird decided to automatically upgrade itself to 102 today.

**Comment by fabian-st** [comment]
An update would be much apprechiated since I have the samme issue as  @dsommers and the rest.

**Comment by C-O-D** [comment]
Me 2 😁

**Comment by balbusm** [comment]
Addon works in the latest release: https://github.com/balbusm/xul-ext-eds-calendar/releases/tag/v1.0.0
Soon it should be available on TB store
