### ISSUE TITLE
Latest version works with TB 107 but need to manual edit .xpi

### ISSUE THREAD

**Issue by cphyc** [balbusm/xul-ext-eds-calendar#51]
This is to let you know the latest version (1.0.1) works like a charm with TB 107 (beta channel). Unfortunately, there is a hard check in place in the xpi that prevents its installation.
I managed to install it after modifying `manifest.json` into
```json
{
  "manifest_version": 2,
  "author": "Mateusz Balbus",
  "homepage_url": "https://github.com/balbusm/xul-ext-eds-calendar",
  "applications": {
    "gecko": {
      "id": "{e6696d02-466a-11e3-a162-04e36188709b}",
      "strict_min_version": "102.0",
      "strict_max_version": "107.*" // <- change here
    }
  },
  ...
}
```
Quick git blame points to https://github.com/balbusm/xul-ext-eds-calendar/commit/3edbff089f907799a657c8ef71a1839603957cd8, but is there any reason to _not_ include versions up to 107?

**Comment by balbusm** [comment]
I bumped up max version on Thunderbird store.
I think it's sufficient. Pls verify.

**Comment by cphyc** [comment]
It looks like it did the trick. If I bump into any issue I'll open another issue.
