### ISSUE TITLE
Gnome applet doesn’t follow the hide/show button in TB

### ISSUE THREAD

**Issue by 945fc41467** [balbusm/xul-ext-eds-calendar#53]
And a second little improvement :

I don’t always want to see all my calendars in the Gnome applet. For exemple on my personal computer I may want to not see my professional calendar, even if it is configured in TB.

In Thunderbird I can hide/show these calender (the little eye next to the calendar). But the Gnome applet doesn’t follow the state of this button.

If I go in Evolution, and change the state here, the Gnome applet is updated.

Maybe it is possible to sync the hide/show state as well ?

**Comment by balbusm** [comment]
Hide/show calendar should work.
What version of the addon, TB are you using?
Could you provide logs?

**Comment by 945fc41467** [comment]
Thunderbird : 102.5.0 (64 bits) « Mozilla Thunderbird for Arch Linux »
EDS calendar integration : 1.0.1
OS : Manjaro

I might be able to provide logs. How can I find these ?

**Comment by balbusm** [comment]
I added you to private [repo](https://github.com/balbusm/xul-ext-eds-calendar-logs). You can post an issue with logs there.

**Comment by 945fc41467** [comment]
You have the log.
I just open TB, went to the calendar tab and toggle show/hide button of two calendars, and close thundebird (actually I closed the terminal which interrupted the process).
After the operation, the to modified calendars appeared in the gnome clock, even if hidden before and after the operation. And I can not hide it with TB now. I have to use evolution.

I assume the show operation trigger the sync, but not the hide operation ?

**Comment by balbusm** [comment]
I've found few issues:
- When you hide calendar it's removed from gnome clock, however after restart it gets populated again - it's a regression
- Adding calendar to gnome clock takes some time (it iterates over all items in the calendar), however removal is very quick. It's possible to quickly carry out hide - show - hide operation which results with show operation overriding hide operation.

**Comment by balbusm** [comment]
@945fc41467 could you check if it's fixed in version [1.0.2](https://github.com/balbusm/xul-ext-eds-calendar/releases/tag/v1.0.2)

**Comment by 945fc41467** [comment]
Now, nothing happen anymore. I can show/hide any calendar in TB. The status of gnome clock doesn’t change. And it stay the same after reboot.

**Comment by balbusm** [comment]
Can you provide logs?

**Comment by 945fc41467** [comment]
Hi,
sorry for the delay. I find some time for more tests last Sunday. Actually, your version 1.0.2 works fine.
The reason why I though it doesn’t work is because it stops to work if I delete the xpi from the download folder after the installation. I guess it is a normal behaviour, Thunderbird doesn’t copy the file in its own folder when we install the extension this way ? If this is right, I think you can close this ticket.

**Comment by balbusm** [comment]
It's Thunderbird thing. 
Closing issue
