### ISSUE TITLE
Thunderbird 115+

### ISSUE THREAD

**Issue by witszymanski** [balbusm/xul-ext-eds-calendar#58]
Hi! 
Any plans to adjust the plugin to 115+ versions? 
Greets
Witek

**Comment by bananabob** [comment]
Like to this as well.

**Comment by C-O-D** [comment]
I'd also appreciate that...

**Comment by Johnnyreyman** [comment]
Is there a plan on updating this extention for TB 115+?

**Comment by balbusm** [comment]
Version [1.1.0](https://github.com/balbusm/xul-ext-eds-calendar/releases/tag/v1.1.0) works with TB115.
It should be available on TB store once it will go through review
